## Basic DataFrame

In [1]:
# install pandas if not

!pip install panda

Collecting panda
  Downloading panda-0.3.1.tar.gz (5.8 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: setuptools in c:\users\acer\anaconda3\lib\site-packages (from panda) (80.9.0)
Requirement already satisfied: requests in c:\users\acer\anaconda3\lib\site-packages (from panda) (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\acer\anaconda3\lib\site-packages (from requests->panda) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\acer\anaconda3\lib\site-packages (from requests->panda) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\acer\anaconda3\lib\site-packages (from requests->panda) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\acer\anaconda3\lib\site-packages (from requests->panda) (2026.1.4)
Building wheels for collected packages: panda
  Building wheel for panda (pyproject.toml): started
  Building wheel for panda (pyproject.toml): finished with status 'done'
  Created wheel for panda: filename=panda-0.3.1-py3-none-any.whl size=7295 sha256=854b34bb53421d2e0128e04e98f2b863922edfd153c3d59f23f0c693d8c1614f
  Stored in directory: c:\users\acer\appdata\local\pip\cache\wheels\53\7c\f7\d3267739bc9dfdfc43724391337c9955e7d5b5830888d735e3
Successfully built panda
Installing collected packages: panda
Successfully installed panda-0.3.1

In [2]:
# import the required library
import pandas as pd

In [36]:
# Read a dataset named: 'imdb-top-1000' and show top 5 rows
df = pd.read_csv("imdb-top-1000.csv")
df

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
996,Giant,1956,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0
997,From Here to Eternity,1953,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0
998,Lifeboat,1944,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
999,The 39 Steps,1935,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0

In [39]:
# How many movies are in the dataset?
#df.count()
len(df)

1000

In [40]:
# What are the column names?
df.columns

Index(['Series_Title', 'Released_Year', 'Runtime', 'Genre', 'IMDB_Rating',
       'Director', 'Star1', 'No_of_Votes', 'Gross', 'Metascore'],
      dtype='object')

In [42]:
# Provide dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Series_Title   1000 non-null   object
 1   Released_Year  1000 non-null   object
 2   Runtime        1000 non-null   int64
 3   Genre          1000 non-null   object
 4   IMDB_Rating    1000 non-null   float64
 5   Director       1000 non-null   object
 6   Star1          1000 non-null   object
 7   No_of_Votes    1000 non-null   int64
 8   Gross          1000 non-null   float64
 9   Metascore      843 non-null    float64
dtypes: float64(3), int64(2), object(5)
memory usage: 78.3+ KB

In [43]:
# What about statistical summary
df.describe()

           Runtime  IMDB_Rating   No_of_Votes         Gross   Metascore
count  1000.000000  1000.000000  1.000000e+03  1.000000e+03  843.000000
mean    122.891000     7.949300  2.736929e+05  1.282781e+08   77.971530
std      28.093671     0.275491  3.273727e+05  2.011110e+08   12.376099
min      45.000000     7.600000  2.508800e+04  1.305000e+03   28.000000
25%     103.000000     7.700000  5.552625e+04  5.012919e+06   70.000000
50%     119.000000     7.900000  1.385485e+05  3.953432e+07   79.000000
75%     137.000000     8.100000  3.741612e+05  1.615997e+08   87.000000
max     321.000000     9.300000  2.343110e+06  9.366622e+08  100.000000

In [45]:
# Check if there is any missing values
df.isna().sum()

Series_Title       0
Released_Year      0
Runtime            0
Genre              0
IMDB_Rating        0
Director           0
Star1              0
No_of_Votes        0
Gross              0
Metascore        157
dtype: int64

In [49]:
# Fill the missing value with the mean of that particular column
df["Metascore"]=df["Metascore"].fillna(df["Metascore"].mean())

In [51]:
# Show movies with rating above 9
condition=df["IMDB_Rating"]>9
df[condition]

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0

In [53]:
# Show 10 most rated movies
df.sort_values("IMDB_Rating", ascending=False).head(10)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
5,The Lord of the Rings: The Return of the King,2003,201,Action,8.9,Peter Jackson,Elijah Wood,1642758,377845905.0,94.0
6,Pulp Fiction,1994,154,Crime,8.9,Quentin Tarantino,John Travolta,1826188,107928762.0,94.0
7,Schindler's List,1993,195,Biography,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
10,The Lord of the Rings: The Fellowship of the Ring,2001,178,Action,8.8,Peter Jackson,Elijah Wood,1661481,315544750.0,92.0
11,Forrest Gump,1994,142,Drama,8.8,Robert Zemeckis,Tom Hanks,1809221,330252182.0,82.0

In [54]:
# Show number of movies done by each star
df["Star1"].value_counts()

Star1
Tom Hanks          12
Robert De Niro     11
Al Pacino          10
Clint Eastwood     10
Humphrey Bogart     9
                   ..
Preity Zinta        1
Javier Bardem       1
Ki-duk Kim          1
Vladimir Garin      1
Robert Donat        1
Name: count, Length: 660, dtype: int64

## GroupBy

In [68]:
# Group all data based on "Genre"
genre=df.groupby("Genre")
genre

In [65]:
# groups
genre.size()

Genre
Action       172
Adventure     72
Animation     82
Biography     88
Comedy       155
Crime        107
Drama        289
Family         2
Fantasy        2
Film-Noir      3
Horror        11
Mystery       12
Thriller       1
Western        4
dtype: int64

In [67]:
# find total number of groups -> len
len(genre)

14

In [69]:
# find items in each group -> size
genre.size()

Genre
Action       172
Adventure     72
Animation     82
Biography     88
Comedy       155
Crime        107
Drama        289
Family         2
Fantasy        2
Film-Noir      3
Horror        11
Mystery       12
Thriller       1
Western        4
dtype: int64

In [17]:
# first()/last()/nth() item

In [18]:
# get_group

In [19]:
# Compute mean for all numerical columns for each genre

In [20]:
# Find top 3 genre by total earning

In [73]:
# Find the genre with highest avg imdb ratings (Task)
genre["IMDB_Rating"].mean().sort_values(ascending=False).head(1)

Genre
Western    8.35
Name: IMDB_Rating, dtype: float64

In [71]:
# Find the most earning actor-director combo
df.groupby(["Star1","Director"])["Gross"].sum().sort_values(ascending=False).head(1)

Star1           Director
Toshirô Mifune  Akira Kurosawa    2.999877e+09
Name: Gross, dtype: float64

In [23]:
# find the highest rated movie of each genre (Hint -> idxmax())

## Merging and Concatenation

In [74]:
# Read datasets
courses = pd.read_csv("courses.csv")
nov = pd.read_csv("reg-month1.csv")
dec = pd.read_csv("reg-month2.csv")
students = pd.read_csv("students.csv")

In [77]:
# Concat 'nov' and 'dec' data and name it 'registration' or 'reg'

reg=pd.concat([nov,dec], ignore_index=True)
reg

    student_id  course_id
0           23          1
1           15          5
2           18          6
3           23          4
4           16          9
5           18          1
6            1          1
7            7          8
8           22          3
9           15          1
10          19          4
11           1          6
12           7         10
13          11          7
14          13          3
15          24          4
16          21          1
17          16          5
18          23          3
19          17          7
20          23          6
21          25          1
22          19          2
23          25         10
24           3          3
25           3          5
26          16          7
27          12         10
28          12          1
29          14          9
30           7          7
31           7          2
32          16          3
33          17         10
34          11          8
35          14          6
36          12          5
37          12          7
38          18          8
39           1         10
40           1          9
41           2          5
42           7          6
43          22          5
44          22          6
45          23          9
46          23          5
47          14          4
48          14          1
49          11         10
50          42          9
51          50          8
52          38          1

In [78]:
# inner join (reg and students)
reg.merge(students, on='student_id', how="inner")

    student_id  course_id                name  partner
0           23          1      Chhavi Lachman       18
1           15          5           Preet Sha       16
2           18          6     Fardeen Mahabir       13
3           23          4      Chhavi Lachman       18
4           16          9        Elias Dodiya       25
5           18          1     Fardeen Mahabir       13
6            1          1       Kailash Harjo       23
7            7          8        Tarun Thaker        9
8           22          3          Yash Sethi       21
9           15          1           Preet Sha       16
10          19          4        Qabeel Raman       12
11           1          6       Kailash Harjo       23
12           7         10        Tarun Thaker        9
13          11          7  David Mukhopadhyay       20
14          13          3      Munni Varghese       24
15          24          4        Radhika Suri       17
16          21          1          Seema Kota       15
17          16          5        Elias Dodiya       25
18          23          3      Chhavi Lachman       18
19          17          7        Yasmin Palan        7
20          23          6      Chhavi Lachman       18
21          25          1     Shashank D’Alia        2
22          19          2        Qabeel Raman       12
23          25         10     Shashank D’Alia        2
24           3          3      Parveen Bhalla        3
25           3          5      Parveen Bhalla        3
26          16          7        Elias Dodiya       25
27          12         10          Radha Dutt       19
28          12          1          Radha Dutt       19
29          14          9    Pranab Natarajan       22
30           7          7        Tarun Thaker        9
31           7          2        Tarun Thaker        9
32          16          3        Elias Dodiya       25
33          17         10        Yasmin Palan        7
34          11          8  David Mukhopadhyay       20
35          14          6    Pranab Natarajan       22
36          12          5          Radha Dutt       19
37          12          7          Radha Dutt       19
38          18          8     Fardeen Mahabir       13
39           1         10       Kailash Harjo       23
40           1          9       Kailash Harjo       23
41           2          5         Esha Butala        1
42           7          6        Tarun Thaker        9
43          22          5          Yash Sethi       21
44          22          6          Yash Sethi       21
45          23          9      Chhavi Lachman       18
46          23          5      Chhavi Lachman       18
47          14          4    Pranab Natarajan       22
48          14          1    Pranab Natarajan       22
49          11         10  David Mukhopadhyay       20

In [79]:
# right join
reg.merge(students, on='student_id', how="right")

    student_id  course_id                name  partner
0            1        1.0       Kailash Harjo       23
1            1        6.0       Kailash Harjo       23
2            1       10.0       Kailash Harjo       23
3            1        9.0       Kailash Harjo       23
4            2        5.0         Esha Butala        1
5            3        3.0      Parveen Bhalla        3
6            3        5.0      Parveen Bhalla        3
7            4        NaN         Marlo Dugal       14
8            5        NaN         Kusum Bahri        6
9            6        NaN  Lakshmi Contractor       10
10           7        8.0        Tarun Thaker        9
11           7       10.0        Tarun Thaker        9
12           7        7.0        Tarun Thaker        9
13           7        2.0        Tarun Thaker        9
14           7        6.0        Tarun Thaker        9
15           8        NaN      Radheshyam Dey        5
16           9        NaN   Nitika Chatterjee        4
17          10        NaN      Aayushman Sant        8
18          11        7.0  David Mukhopadhyay       20
19          11        8.0  David Mukhopadhyay       20
20          11       10.0  David Mukhopadhyay       20
21          12       10.0          Radha Dutt       19
22          12        1.0          Radha Dutt       19
23          12        5.0          Radha Dutt       19
24          12        7.0          Radha Dutt       19
25          13        3.0      Munni Varghese       24
26          14        9.0    Pranab Natarajan       22
27          14        6.0    Pranab Natarajan       22
28          14        4.0    Pranab Natarajan       22
29          14        1.0    Pranab Natarajan       22
30          15        5.0           Preet Sha       16
31          15        1.0           Preet Sha       16
32          16        9.0        Elias Dodiya       25
33          16        5.0        Elias Dodiya       25
34          16        7.0        Elias Dodiya       25
35          16        3.0        Elias Dodiya       25
36          17        7.0        Yasmin Palan        7
37          17       10.0        Yasmin Palan        7
38          18        6.0     Fardeen Mahabir       13
39          18        1.0     Fardeen Mahabir       13
40          18        8.0     Fardeen Mahabir       13
41          19        4.0        Qabeel Raman       12
42          19        2.0        Qabeel Raman       12
43          20        NaN       Hanuman Hegde       11
44          21        1.0          Seema Kota       15
45          22        3.0          Yash Sethi       21
46          22        5.0          Yash Sethi       21
47          22        6.0          Yash Sethi       21
48          23        1.0      Chhavi Lachman       18
49          23        4.0      Chhavi Lachman       18
50          23        3.0      Chhavi Lachman       18
51          23        6.0      Chhavi Lachman       18
52          23        9.0      Chhavi Lachman       18
53          23        5.0      Chhavi Lachman       18
54          24        4.0        Radhika Suri       17
55          25        1.0     Shashank D’Alia        2
56          25       10.0     Shashank D’Alia        2

In [80]:
# left join
reg.merge(students, on='student_id', how="left")

    student_id  course_id                name  partner
0           23          1      Chhavi Lachman     18.0
1           15          5           Preet Sha     16.0
2           18          6     Fardeen Mahabir     13.0
3           23          4      Chhavi Lachman     18.0
4           16          9        Elias Dodiya     25.0
5           18          1     Fardeen Mahabir     13.0
6            1          1       Kailash Harjo     23.0
7            7          8        Tarun Thaker      9.0
8           22          3          Yash Sethi     21.0
9           15          1           Preet Sha     16.0
10          19          4        Qabeel Raman     12.0
11           1          6       Kailash Harjo     23.0
12           7         10        Tarun Thaker      9.0
13          11          7  David Mukhopadhyay     20.0
14          13          3      Munni Varghese     24.0
15          24          4        Radhika Suri     17.0
16          21          1          Seema Kota     15.0
17          16          5        Elias Dodiya     25.0
18          23          3      Chhavi Lachman     18.0
19          17          7        Yasmin Palan      7.0
20          23          6      Chhavi Lachman     18.0
21          25          1     Shashank D’Alia      2.0
22          19          2        Qabeel Raman     12.0
23          25         10     Shashank D’Alia      2.0
24           3          3      Parveen Bhalla      3.0
25           3          5      Parveen Bhalla      3.0
26          16          7        Elias Dodiya     25.0
27          12         10          Radha Dutt     19.0
28          12          1          Radha Dutt     19.0
29          14          9    Pranab Natarajan     22.0
30           7          7        Tarun Thaker      9.0
31           7          2        Tarun Thaker      9.0
32          16          3        Elias Dodiya     25.0
33          17         10        Yasmin Palan      7.0
34          11          8  David Mukhopadhyay     20.0
35          14          6    Pranab Natarajan     22.0
36          12          5          Radha Dutt     19.0
37          12          7          Radha Dutt     19.0
38          18          8     Fardeen Mahabir     13.0
39           1         10       Kailash Harjo     23.0
40           1          9       Kailash Harjo     23.0
41           2          5         Esha Butala      1.0
42           7          6        Tarun Thaker      9.0
43          22          5          Yash Sethi     21.0
44          22          6          Yash Sethi     21.0
45          23          9      Chhavi Lachman     18.0
46          23          5      Chhavi Lachman     18.0
47          14          4    Pranab Natarajan     22.0
48          14          1    Pranab Natarajan     22.0
49          11         10  David Mukhopadhyay     20.0
50          42          9                 NaN      NaN
51          50          8                 NaN      NaN
52          38          1                 NaN      NaN

In [81]:
# outer join
reg.merge(students, on='student_id', how="outer")

    student_id  course_id                name  partner
0            1        1.0       Kailash Harjo     23.0
1            1        6.0       Kailash Harjo     23.0
2            1       10.0       Kailash Harjo     23.0
3            1        9.0       Kailash Harjo     23.0
4            2        5.0         Esha Butala      1.0
5            3        3.0      Parveen Bhalla      3.0
6            3        5.0      Parveen Bhalla      3.0
7            4        NaN         Marlo Dugal     14.0
8            5        NaN         Kusum Bahri      6.0
9            6        NaN  Lakshmi Contractor     10.0
10           7        8.0        Tarun Thaker      9.0
11           7       10.0        Tarun Thaker      9.0
12           7        7.0        Tarun Thaker      9.0
13           7        2.0        Tarun Thaker      9.0
14           7        6.0        Tarun Thaker      9.0
15           8        NaN      Radheshyam Dey      5.0
16           9        NaN   Nitika Chatterjee      4.0
17          10        NaN      Aayushman Sant      8.0
18          11        7.0  David Mukhopadhyay     20.0
19          11        8.0  David Mukhopadhyay     20.0
20          11       10.0  David Mukhopadhyay     20.0
21          12       10.0          Radha Dutt     19.0
22          12        1.0          Radha Dutt     19.0
23          12        5.0          Radha Dutt     19.0
24          12        7.0          Radha Dutt     19.0
25          13        3.0      Munni Varghese     24.0
26          14        9.0    Pranab Natarajan     22.0
27          14        6.0    Pranab Natarajan     22.0
28          14        4.0    Pranab Natarajan     22.0
29          14        1.0    Pranab Natarajan     22.0
30          15        5.0           Preet Sha     16.0
31          15        1.0           Preet Sha     16.0
32          16        9.0        Elias Dodiya     25.0
33          16        5.0        Elias Dodiya     25.0
34          16        7.0        Elias Dodiya     25.0
35          16        3.0        Elias Dodiya     25.0
36          17        7.0        Yasmin Palan      7.0
37          17       10.0        Yasmin Palan      7.0
38          18        6.0     Fardeen Mahabir     13.0
39          18        1.0     Fardeen Mahabir     13.0
40          18        8.0     Fardeen Mahabir     13.0
41          19        4.0        Qabeel Raman     12.0
42          19        2.0        Qabeel Raman     12.0
43          20        NaN       Hanuman Hegde     11.0
44          21        1.0          Seema Kota     15.0
45          22        3.0          Yash Sethi     21.0
46          22        5.0          Yash Sethi     21.0
47          22        6.0          Yash Sethi     21.0
48          23        1.0      Chhavi Lachman     18.0
49          23        4.0      Chhavi Lachman     18.0
50          23        3.0      Chhavi Lachman     18.0
51          23        6.0      Chhavi Lachman     18.0
52          23        9.0      Chhavi Lachman     18.0
53          23        5.0      Chhavi Lachman     18.0
54          24        4.0        Radhika Suri     17.0
55          25        1.0     Shashank D’Alia      2.0
56          25       10.0     Shashank D’Alia      2.0
57          38        1.0                 NaN      NaN
58          42        9.0                 NaN      NaN
59          50        8.0                 NaN      NaN

In [84]:
# Find total revenue generated
courses.merge(reg, on ="course_id")["price"].sum()

np.int64(154247)

In [87]:
# Print the registration table 
# cols -> name -> course -> price
students.merge(reg, on="student_id").merge(courses, on="course_id")[["name","course_name","price"]]

                  name       course_name  price
0        Kailash Harjo            python   2499
1        Kailash Harjo          power bi   1899
2        Kailash Harjo           pyspark   2499
3        Kailash Harjo            plotly    699
4          Esha Butala           tableau   2499
5       Parveen Bhalla     data analysis   4999
6       Parveen Bhalla           tableau   2499
7         Tarun Thaker            pandas   1099
8         Tarun Thaker           pyspark   2499
9         Tarun Thaker          ms sxcel   1599
10        Tarun Thaker               sql   3499
11        Tarun Thaker          power bi   1899
12  David Mukhopadhyay          ms sxcel   1599
13  David Mukhopadhyay            pandas   1099
14  David Mukhopadhyay           pyspark   2499
15          Radha Dutt           pyspark   2499
16          Radha Dutt            python   2499
17          Radha Dutt           tableau   2499
18          Radha Dutt          ms sxcel   1599
19      Munni Varghese     data analysis   4999
20    Pranab Natarajan            plotly    699
21    Pranab Natarajan          power bi   1899
22    Pranab Natarajan  machine learning   9999
23    Pranab Natarajan            python   2499
24           Preet Sha           tableau   2499
25           Preet Sha            python   2499
26        Elias Dodiya            plotly    699
27        Elias Dodiya           tableau   2499
28        Elias Dodiya          ms sxcel   1599
29        Elias Dodiya     data analysis   4999
30        Yasmin Palan          ms sxcel   1599
31        Yasmin Palan           pyspark   2499
32     Fardeen Mahabir          power bi   1899
33     Fardeen Mahabir            python   2499
34     Fardeen Mahabir            pandas   1099
35        Qabeel Raman  machine learning   9999
36        Qabeel Raman               sql   3499
37          Seema Kota            python   2499
38          Yash Sethi     data analysis   4999
39          Yash Sethi           tableau   2499
40          Yash Sethi          power bi   1899
41      Chhavi Lachman            python   2499
42      Chhavi Lachman  machine learning   9999
43      Chhavi Lachman     data analysis   4999
44      Chhavi Lachman          power bi   1899
45      Chhavi Lachman            plotly    699
46      Chhavi Lachman           tableau   2499
47        Radhika Suri  machine learning   9999
48     Shashank D’Alia            python   2499
49     Shashank D’Alia           pyspark   2499

In [32]:
# Plot bar chart for revenue/course (revenue per course)

In [92]:
# Print student name -> partner name for all enrolled students
# self join
table = students.merge(students, left_on="partner", right_on="student_id")
table[["name_x","name_y"]].rename(columns={"name_x":"Students","name_y":"Partner"})

              Students             Partner
0        Kailash Harjo      Chhavi Lachman
1          Esha Butala       Kailash Harjo
2       Parveen Bhalla      Parveen Bhalla
3          Marlo Dugal    Pranab Natarajan
4          Kusum Bahri  Lakshmi Contractor
5   Lakshmi Contractor      Aayushman Sant
6         Tarun Thaker   Nitika Chatterjee
7       Radheshyam Dey         Kusum Bahri
8    Nitika Chatterjee         Marlo Dugal
9       Aayushman Sant      Radheshyam Dey
10  David Mukhopadhyay       Hanuman Hegde
11          Radha Dutt        Qabeel Raman
12      Munni Varghese        Radhika Suri
13    Pranab Natarajan          Yash Sethi
14           Preet Sha        Elias Dodiya
15        Elias Dodiya     Shashank D’Alia
16        Yasmin Palan        Tarun Thaker
17     Fardeen Mahabir      Munni Varghese
18        Qabeel Raman          Radha Dutt
19       Hanuman Hegde  David Mukhopadhyay
20          Seema Kota           Preet Sha
21          Yash Sethi          Seema Kota
22      Chhavi Lachman     Fardeen Mahabir
23        Radhika Suri        Yasmin Palan
24     Shashank D’Alia         Esha Butala

In [34]:
# Find top 3 students who did most number of enrollments

*Happy Coding 🎉🎉*